# Generated by Django 5.1.6 on 2025-02-21 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A1', '0003_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
