# Generated by Django 5.1.6 on 2025-02-22 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A1', '0006_billing'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='stripe_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
